name: MCDiscordVerify
version: @version@
main: space.mori.mcdiscordverify.bukkit.MCDiscordVerify
api-version: 1.18
authors:
  - dalbodeule
depend:
  - kotlin-stdlib
commands:
  discord:
    permission: mcdiscordverify.discord
permissions:
  mcdiscordverify.discord:
    description: Allows discord command
    default: true
  mcdiscordverify.reload:
    description: Allows reload subcommand
    default: op