name: MCDiscordVerify
version: @version@
main: space.mori.mcdiscordverify.MCDiscordVerify
api-version: 1.14
depend:
authors:
  - dalbodeule
commands:
  discord:
    usage: "Usage: /<command>"
    permission: mcdiscordverify.discord
permissions:
  mcdiscordverify.discord:
    description: Allows discord command
    default: true