name: MCDiscordVerify
version: @version@
main: space.mori.mcdiscordverify.MCDiscordVerify
api-version: 1.17
authors:
  - dalbodeule
commands:
  discord:
    permission: mcdiscordverify.discord
permissions:
  mcdiscordverify.discord:
    description: Allows discord command
    default: true
